// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.4
// source: visual_message.proto

package visual

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	common "proxy-system-backend/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisualMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 插件生成的唯一 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 所属连接
	ConnId string `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	// 时间戳（通常继承 RawPacket）
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 数据方向
	Direction common.PacketDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=common.PacketDirection" json:"direction,omitempty"`
	// 消息名（LoginReq / Move / SyncData）
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// 分类（auth / battle / sync / chat）
	Category string `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	// 一行摘要（UI 列表用）
	Summary string `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	// 解码后的字段（适合树形展示）
	Fields *structpb.Struct `protobuf:"bytes,8,opt,name=fields,proto3" json:"fields,omitempty"`
	// 原始数据（可选，用于导出 / 回放）
	Raw []byte `protobuf:"bytes,9,opt,name=raw,proto3" json:"raw,omitempty"`
	// 标签（搜索 / 高亮 / 规则）
	Tags          []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualMessage) Reset() {
	*x = VisualMessage{}
	mi := &file_visual_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualMessage) ProtoMessage() {}

func (x *VisualMessage) ProtoReflect() protoreflect.Message {
	mi := &file_visual_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualMessage.ProtoReflect.Descriptor instead.
func (*VisualMessage) Descriptor() ([]byte, []int) {
	return file_visual_message_proto_rawDescGZIP(), []int{0}
}

func (x *VisualMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VisualMessage) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *VisualMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *VisualMessage) GetDirection() common.PacketDirection {
	if x != nil {
		return x.Direction
	}
	return common.PacketDirection(0)
}

func (x *VisualMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VisualMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VisualMessage) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *VisualMessage) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *VisualMessage) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *VisualMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_visual_message_proto protoreflect.FileDescriptor

const file_visual_message_proto_rawDesc = "" +
	"\n" +
	"\x14visual_message.proto\x12\x06visual\x1a\fcommon.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xae\x02\n" +
	"\rVisualMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x125\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x17.common.PacketDirectionR\tdirection\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12/\n" +
	"\x06fields\x18\b \x01(\v2\x17.google.protobuf.StructR\x06fields\x12\x10\n" +
	"\x03raw\x18\t \x01(\fR\x03raw\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tagsB*Z(proxy-system-backend/proto/visual;visualb\x06proto3"

var (
	file_visual_message_proto_rawDescOnce sync.Once
	file_visual_message_proto_rawDescData []byte
)

func file_visual_message_proto_rawDescGZIP() []byte {
	file_visual_message_proto_rawDescOnce.Do(func() {
		file_visual_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visual_message_proto_rawDesc), len(file_visual_message_proto_rawDesc)))
	})
	return file_visual_message_proto_rawDescData
}

var file_visual_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_visual_message_proto_goTypes = []any{
	(*VisualMessage)(nil),       // 0: visual.VisualMessage
	(common.PacketDirection)(0), // 1: common.PacketDirection
	(*structpb.Struct)(nil),     // 2: google.protobuf.Struct
}
var file_visual_message_proto_depIdxs = []int32{
	1, // 0: visual.VisualMessage.direction:type_name -> common.PacketDirection
	2, // 1: visual.VisualMessage.fields:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_visual_message_proto_init() }
func file_visual_message_proto_init() {
	if File_visual_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visual_message_proto_rawDesc), len(file_visual_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_visual_message_proto_goTypes,
		DependencyIndexes: file_visual_message_proto_depIdxs,
		MessageInfos:      file_visual_message_proto_msgTypes,
	}.Build()
	File_visual_message_proto = out.File
	file_visual_message_proto_goTypes = nil
	file_visual_message_proto_depIdxs = nil
}
