// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.4
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketDirection int32

const (
	PacketDirection_PACKET_DIRECTION_UNKNOWN PacketDirection = 0
	PacketDirection_PACKET_DIRECTION_C2S     PacketDirection = 1 // client -> server
	PacketDirection_PACKET_DIRECTION_S2C     PacketDirection = 2 // server -> client
)

// Enum value maps for PacketDirection.
var (
	PacketDirection_name = map[int32]string{
		0: "PACKET_DIRECTION_UNKNOWN",
		1: "PACKET_DIRECTION_C2S",
		2: "PACKET_DIRECTION_S2C",
	}
	PacketDirection_value = map[string]int32{
		"PACKET_DIRECTION_UNKNOWN": 0,
		"PACKET_DIRECTION_C2S":     1,
		"PACKET_DIRECTION_S2C":     2,
	}
)

func (x PacketDirection) Enum() *PacketDirection {
	p := new(PacketDirection)
	*p = x
	return p
}

func (x PacketDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (PacketDirection) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x PacketDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketDirection.Descriptor instead.
func (PacketDirection) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type TransportType int32

const (
	TransportType_TRANSPORT_UNKNOWN TransportType = 0
	TransportType_TRANSPORT_TCP     TransportType = 1
	TransportType_TRANSPORT_UDP     TransportType = 2
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_UNKNOWN",
		1: "TRANSPORT_TCP",
		2: "TRANSPORT_UDP",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_UNKNOWN": 0,
		"TRANSPORT_TCP":     1,
		"TRANSPORT_UDP":     2,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common*c\n" +
	"\x0fPacketDirection\x12\x1c\n" +
	"\x18PACKET_DIRECTION_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14PACKET_DIRECTION_C2S\x10\x01\x12\x18\n" +
	"\x14PACKET_DIRECTION_S2C\x10\x02*L\n" +
	"\rTransportType\x12\x15\n" +
	"\x11TRANSPORT_UNKNOWN\x10\x00\x12\x11\n" +
	"\rTRANSPORT_TCP\x10\x01\x12\x11\n" +
	"\rTRANSPORT_UDP\x10\x02B*Z(proxy-system-backend/proto/common;commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_goTypes = []any{
	(PacketDirection)(0), // 0: common.PacketDirection
	(TransportType)(0),   // 1: common.TransportType
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
