// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.4
// source: plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	raw "proxy-system-backend/proto/raw"
	visual "proxy-system-backend/proto/visual"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Packet *raw.RawPacket         `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	// 由主程序选择的协议版本
	ProtocolId    string `protobuf:"bytes,2,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRequest) Reset() {
	*x = DecodeRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRequest) ProtoMessage() {}

func (x *DecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRequest.ProtoReflect.Descriptor instead.
func (*DecodeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *DecodeRequest) GetPacket() *raw.RawPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *DecodeRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

type DecodeResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Messages      []*visual.VisualMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeResponse) Reset() {
	*x = DecodeResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResponse) ProtoMessage() {}

func (x *DecodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResponse.ProtoReflect.Descriptor instead.
func (*DecodeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *DecodeResponse) GetMessages() []*visual.VisualMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PluginInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Game        string                 `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author      string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// 支持的协议版本
	Protocols     []*ProtocolDesc `protobuf:"bytes,6,rep,name=protocols,proto3" json:"protocols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetProtocols() []*ProtocolDesc {
	if x != nil {
		return x.Protocols
	}
	return nil
}

type ProtocolDesc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // v1 / v2 / cn_2024
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolDesc) Reset() {
	*x = ProtocolDesc{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolDesc) ProtoMessage() {}

func (x *ProtocolDesc) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolDesc.ProtoReflect.Descriptor instead.
func (*ProtocolDesc) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolDesc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtocolDesc) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ResetConnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetConnRequest) Reset() {
	*x = ResetConnRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetConnRequest) ProtoMessage() {}

func (x *ResetConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetConnRequest.ProtoReflect.Descriptor instead.
func (*ResetConnRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ResetConnRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x06plugin\x1a\x10raw_packet.proto\x1a\x14visual_message.proto\x1a\x1bgoogle/protobuf/empty.proto\"X\n" +
	"\rDecodeRequest\x12&\n" +
	"\x06packet\x18\x01 \x01(\v2\x0e.raw.RawPacketR\x06packet\x12\x1f\n" +
	"\vprotocol_id\x18\x02 \x01(\tR\n" +
	"protocolId\"C\n" +
	"\x0eDecodeResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.visual.VisualMessageR\bmessages\"\xbc\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x122\n" +
	"\tprotocols\x18\x06 \x03(\v2\x14.plugin.ProtocolDescR\tprotocols\"A\n" +
	"\fProtocolDesc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"+\n" +
	"\x10ResetConnRequest\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId2\xc0\x01\n" +
	"\x12GameProtocolPlugin\x122\n" +
	"\x04Info\x12\x16.google.protobuf.Empty\x1a\x12.plugin.PluginInfo\x127\n" +
	"\x06Decode\x12\x15.plugin.DecodeRequest\x1a\x16.plugin.DecodeResponse\x12=\n" +
	"\tResetConn\x12\x18.plugin.ResetConnRequest\x1a\x16.google.protobuf.EmptyB*Z(proxy-system-backend/proto/plugin;pluginb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_proto_goTypes = []any{
	(*DecodeRequest)(nil),        // 0: plugin.DecodeRequest
	(*DecodeResponse)(nil),       // 1: plugin.DecodeResponse
	(*PluginInfo)(nil),           // 2: plugin.PluginInfo
	(*ProtocolDesc)(nil),         // 3: plugin.ProtocolDesc
	(*ResetConnRequest)(nil),     // 4: plugin.ResetConnRequest
	(*raw.RawPacket)(nil),        // 5: raw.RawPacket
	(*visual.VisualMessage)(nil), // 6: visual.VisualMessage
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_plugin_proto_depIdxs = []int32{
	5, // 0: plugin.DecodeRequest.packet:type_name -> raw.RawPacket
	6, // 1: plugin.DecodeResponse.messages:type_name -> visual.VisualMessage
	3, // 2: plugin.PluginInfo.protocols:type_name -> plugin.ProtocolDesc
	7, // 3: plugin.GameProtocolPlugin.Info:input_type -> google.protobuf.Empty
	0, // 4: plugin.GameProtocolPlugin.Decode:input_type -> plugin.DecodeRequest
	4, // 5: plugin.GameProtocolPlugin.ResetConn:input_type -> plugin.ResetConnRequest
	2, // 6: plugin.GameProtocolPlugin.Info:output_type -> plugin.PluginInfo
	1, // 7: plugin.GameProtocolPlugin.Decode:output_type -> plugin.DecodeResponse
	7, // 8: plugin.GameProtocolPlugin.ResetConn:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
