// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.4
// source: plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameProtocolPlugin_Info_FullMethodName      = "/plugin.GameProtocolPlugin/Info"
	GameProtocolPlugin_Decode_FullMethodName    = "/plugin.GameProtocolPlugin/Decode"
	GameProtocolPlugin_ResetConn_FullMethodName = "/plugin.GameProtocolPlugin/ResetConn"
)

// GameProtocolPluginClient is the client API for GameProtocolPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameProtocolPluginClient interface {
	// 插件元信息
	Info(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	// 解码入口
	Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error)
	// 连接重置（断线 / 回放重置）
	ResetConn(ctx context.Context, in *ResetConnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type gameProtocolPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewGameProtocolPluginClient(cc grpc.ClientConnInterface) GameProtocolPluginClient {
	return &gameProtocolPluginClient{cc}
}

func (c *gameProtocolPluginClient) Info(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, GameProtocolPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameProtocolPluginClient) Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeResponse)
	err := c.cc.Invoke(ctx, GameProtocolPlugin_Decode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameProtocolPluginClient) ResetConn(ctx context.Context, in *ResetConnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GameProtocolPlugin_ResetConn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameProtocolPluginServer is the server API for GameProtocolPlugin service.
// All implementations must embed UnimplementedGameProtocolPluginServer
// for forward compatibility.
type GameProtocolPluginServer interface {
	// 插件元信息
	Info(context.Context, *emptypb.Empty) (*PluginInfo, error)
	// 解码入口
	Decode(context.Context, *DecodeRequest) (*DecodeResponse, error)
	// 连接重置（断线 / 回放重置）
	ResetConn(context.Context, *ResetConnRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedGameProtocolPluginServer()
}

// UnimplementedGameProtocolPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameProtocolPluginServer struct{}

func (UnimplementedGameProtocolPluginServer) Info(context.Context, *emptypb.Empty) (*PluginInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedGameProtocolPluginServer) Decode(context.Context, *DecodeRequest) (*DecodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decode not implemented")
}
func (UnimplementedGameProtocolPluginServer) ResetConn(context.Context, *ResetConnRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetConn not implemented")
}
func (UnimplementedGameProtocolPluginServer) mustEmbedUnimplementedGameProtocolPluginServer() {}
func (UnimplementedGameProtocolPluginServer) testEmbeddedByValue()                            {}

// UnsafeGameProtocolPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameProtocolPluginServer will
// result in compilation errors.
type UnsafeGameProtocolPluginServer interface {
	mustEmbedUnimplementedGameProtocolPluginServer()
}

func RegisterGameProtocolPluginServer(s grpc.ServiceRegistrar, srv GameProtocolPluginServer) {
	// If the following call pancis, it indicates UnimplementedGameProtocolPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameProtocolPlugin_ServiceDesc, srv)
}

func _GameProtocolPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameProtocolPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameProtocolPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameProtocolPluginServer).Info(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameProtocolPlugin_Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameProtocolPluginServer).Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameProtocolPlugin_Decode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameProtocolPluginServer).Decode(ctx, req.(*DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameProtocolPlugin_ResetConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetConnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameProtocolPluginServer).ResetConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameProtocolPlugin_ResetConn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameProtocolPluginServer).ResetConn(ctx, req.(*ResetConnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameProtocolPlugin_ServiceDesc is the grpc.ServiceDesc for GameProtocolPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameProtocolPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.GameProtocolPlugin",
	HandlerType: (*GameProtocolPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _GameProtocolPlugin_Info_Handler,
		},
		{
			MethodName: "Decode",
			Handler:    _GameProtocolPlugin_Decode_Handler,
		},
		{
			MethodName: "ResetConn",
			Handler:    _GameProtocolPlugin_ResetConn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
