// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.4
// source: raw_packet.proto

package raw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "proxy-system-backend/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 连接唯一标识（由代理层生成）
	ConnId string `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	// 时间戳（建议统一：UnixNano）
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 数据方向
	Direction common.PacketDirection `protobuf:"varint,3,opt,name=direction,proto3,enum=common.PacketDirection" json:"direction,omitempty"`
	// 传输层协议
	Transport common.TransportType `protobuf:"varint,4,opt,name=transport,proto3,enum=common.TransportType" json:"transport,omitempty"`
	// 原始 payload
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// 可选：连接信息（主要用于 UI / 调试）
	LocalAddr     string `protobuf:"bytes,6,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	RemoteAddr    string `protobuf:"bytes,7,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPacket) Reset() {
	*x = RawPacket{}
	mi := &file_raw_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPacket) ProtoMessage() {}

func (x *RawPacket) ProtoReflect() protoreflect.Message {
	mi := &file_raw_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPacket.ProtoReflect.Descriptor instead.
func (*RawPacket) Descriptor() ([]byte, []int) {
	return file_raw_packet_proto_rawDescGZIP(), []int{0}
}

func (x *RawPacket) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *RawPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RawPacket) GetDirection() common.PacketDirection {
	if x != nil {
		return x.Direction
	}
	return common.PacketDirection(0)
}

func (x *RawPacket) GetTransport() common.TransportType {
	if x != nil {
		return x.Transport
	}
	return common.TransportType(0)
}

func (x *RawPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RawPacket) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *RawPacket) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

var File_raw_packet_proto protoreflect.FileDescriptor

const file_raw_packet_proto_rawDesc = "" +
	"\n" +
	"\x10raw_packet.proto\x12\x03raw\x1a\fcommon.proto\"\x88\x02\n" +
	"\tRawPacket\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x125\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x17.common.PacketDirectionR\tdirection\x123\n" +
	"\ttransport\x18\x04 \x01(\x0e2\x15.common.TransportTypeR\ttransport\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x06 \x01(\tR\tlocalAddr\x12\x1f\n" +
	"\vremote_addr\x18\a \x01(\tR\n" +
	"remoteAddrB$Z\"proxy-system-backend/proto/raw;rawb\x06proto3"

var (
	file_raw_packet_proto_rawDescOnce sync.Once
	file_raw_packet_proto_rawDescData []byte
)

func file_raw_packet_proto_rawDescGZIP() []byte {
	file_raw_packet_proto_rawDescOnce.Do(func() {
		file_raw_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raw_packet_proto_rawDesc), len(file_raw_packet_proto_rawDesc)))
	})
	return file_raw_packet_proto_rawDescData
}

var file_raw_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_raw_packet_proto_goTypes = []any{
	(*RawPacket)(nil),           // 0: raw.RawPacket
	(common.PacketDirection)(0), // 1: common.PacketDirection
	(common.TransportType)(0),   // 2: common.TransportType
}
var file_raw_packet_proto_depIdxs = []int32{
	1, // 0: raw.RawPacket.direction:type_name -> common.PacketDirection
	2, // 1: raw.RawPacket.transport:type_name -> common.TransportType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_raw_packet_proto_init() }
func file_raw_packet_proto_init() {
	if File_raw_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raw_packet_proto_rawDesc), len(file_raw_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raw_packet_proto_goTypes,
		DependencyIndexes: file_raw_packet_proto_depIdxs,
		MessageInfos:      file_raw_packet_proto_msgTypes,
	}.Build()
	File_raw_packet_proto = out.File
	file_raw_packet_proto_goTypes = nil
	file_raw_packet_proto_depIdxs = nil
}
